apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: helix-participant-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helix-participant-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: jobs-number
      target:
        type: AverageValue
        averageValue: 1
